export const ROUTE_DEFS = [
  { path: "/" },
  { path: "/preference" },
  { path: "/shortcuts" },
  { path: "/api-providers" },
  { path: "/custom-actions" },
  { path: "/notebase" },
  // 保存成功后的「打开笔记库」是带 id 的深链，走同一个页面
  { path: "/notebase/:notebaseId" },
  { path: "/review" },
  { path: "/sentence-practice" },
  { path: "/stats" },
  { path: "/page-translation" },
  { path: "/video-subtitles" },
  { path: "/floating-button" },
  { path: "/selection-toolbar" },
  { path: "/context-menu" },
  { path: "/input-translation" },
  { path: "/tts" },

  // Detail pages drilled into from a `ConfigNavItem`. They own no sidebar entry — the
  // sidebar lists its links itself — but route exactly like any other page.
  { path: "/preference/config-backup" },
  { path: "/preference/extension-activation" },
  { path: "/page-translation/custom-css" },
  { path: "/page-translation/prompts" },
  { path: "/page-translation/translation-control" },
  { path: "/page-translation/translation-control/auto-translate-websites" },
  { path: "/page-translation/translation-control/never-auto-translate-websites" },
  { path: "/page-translation/translation-control/site-rules" },
  { path: "/page-translation/translation-queue" },
  { path: "/video-subtitles/style" },
  { path: "/video-subtitles/style/custom-css" },
  { path: "/video-subtitles/prompts" },
  { path: "/video-subtitles/subtitles-queue" },
] as const
